### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by reduxionist** [tsbarnes/chrome-sipml5#1]
Just curious to know what the build status on this project is. I installed and configured it with a known working SIP account and no dice; before I spent any time debugging the situation I thought I'd check on where you're at with this code.

Thanks!
Jonathan

**Comment by tsbarnes** [comment]
I've only been able to test it with sip2sip.info and ekiga.net, but it works with both of those.  What SIP provider are you using?

**Comment by reduxionist** [comment]
I'm using an account on my own Asterisk server, which works using x-lite and zoiper. Given that your examples are domain names, do you think it's possible my issue might be that I'm using a direct IP address?

I see no registration attempt from the client in my Asterisk server's debug output when I click connect (or save config) in the client. 

Any restrictions on Chrome version, like requires Chrome Canary or anything? I'm testing with normal release version...

Thanks for the speedy response!

**Comment by tsbarnes** [comment]
It should work with Chrome stable, and the use of an IP shouldn't be a problem.  Can you test if your set up works on [sipml5.org](http://sipml5.org/)?  That's the demo site of the SIP library this extension uses, so it'll help figure out if the problem is in the extension or the library.

**Comment by reduxionist** [comment]
My setup does work with sipml5.org; when I enter the same settings there as used with the extension I see the following appear in my Asterisk server's logs: 

Registered SIP 'xxxxxx' at yyy.yyy.yyy.yyy:yyyyy

And more depending on the level of verbosity I request.

There's nothing in the logs when using all the same settings in the extension. 

If this is something you have the time and desire to debug further, I'd be happy to give you a SIP account on my Asterisk server, it has no PSTN connectivity so you can't run up any sort of expenses through it... ;)

Thanks in any case!=

**Comment by tsbarnes** [comment]
Sure, just let me know the settings for the account.

**Comment by reduxionist** [comment]
I'm on vacation this week and away from home, but will get back to you next week when I return, thanks very much for your continued help!

**Comment by santosh35** [comment]
Hi,

I have newly installed this chrome extension and it looks good when doing out and in calls.
But when a call comes I cannot accept or reject the calls it give me the below error

Error in event handler for notifications.onButtonClicked: TypeError: Cannot read property 'accept' of undefined
    at chrome-extension://clomghcnjbcjliepjgaejblaafnekbmf/js/background.js:46:32

**Comment by reduxionist** [comment]
@tsbarnes As it happens the component of the project that I was using this extension to test with got mothballed, so no need to invest any further time debugging a moot point. Thanks for your support though!

@santosh35 I recommend you open a separate issue for the error you encountered.
