### ISSUE TITLE
Cannot Accept or Reject Calls on the Chrome Extension

### ISSUE THREAD

**Issue by santosh35** [tsbarnes/chrome-sipml5#2]
Hi,

I have newly installed this chrome extension and it looks good when doing out and in calls.
But when a call comes I cannot accept or reject the calls it give me the below error

Error in event handler for notifications.onButtonClicked: TypeError: Cannot read property 'accept' of undefined
at chrome-extension://clomghcnjbcjliepjgaejblaafnekbmf/js/background.js:46:32

**Comment by tsbarnes** [comment]
Odd, I'll look into it.  What version of Chrome are you using?

**Comment by santosh35** [comment]
HI,

Chrome Version Version 40.0.2214.93 m

Install everything on VMWare.
And today I will be doing it on the Live Server with Ubuntu 12.04 LTS on it.

Hoping to hear soon from you.

**Comment by santosh35** [comment]
Hi,

I had now installed everything on a Live IP machine with Ubuntu 12.04 Machine.
M getting the same error can you please help me.

**Comment by tsbarnes** [comment]
I'm still looking into this, but I'm having trouble reproducing the error.  It seems like the extension isn't initializing properly though (the Javascript is loading in the wrong order, most likely).  I'm looking into ways to prevent that from happening, hopefully I'll have it worked out soon.

**Comment by santosh35** [comment]
Hi,
Just provide the Link for Step-By-Step guide to do a proper installation with Asterisk 13.0 and then try your chrome extension

**Comment by tsbarnes** [comment]
Haven't heard anything on this in over a year, and I can't reproduce the issue, so I'm closing it.
